version: 2.1
executors:
  lambda-executor:
    docker:
      - image: circleci/python:3.7.2
#    working_directory: /tmp

jobs:
  test-local-venv:
    executor: lambda-executor
    #    docker:
    #      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: run tests local venv
          command: |
            make test-all-venv
          environment:
            AWS_SECRET_ACCESS_KEY: "This_is_a_key"
            AWS_ACCESS_KEY_ID: "This_is_an_Id"
            BOTO_CONFIG: /dev/null
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: pytest.report.html
          destination: pytest.report.html

  build-lambda-packages:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build lambda packages
          command: |
            make create-packages
      - persist_to_workspace:
          root: .\terraform\shopper
          paths:
            - .\terraform\shopper\packages
            - .\terraform\shopper\variable.version.tf

  test-terraform-modules:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .\terraform\shopper
      - run:
          name: test terraform modules
          command: |
            make test-terraform-modules
      - store_artifacts:
          path: ./terraform/pytest.report.html
          destination: pytest.report.html

#      - persist_to_workspace:
#          root: packages
#          # Must be relative path from root
#          paths:
#            - .


#  push-lambda-packages-to-s3:
#    executor: lambda-executor
#    steps:
#      - attach_workspace:
#          at: .
#      - attach_workspace:
#          at: packages
#      - run:
#          name: Check package content
#          command: |
#            make --trace publish-packages-to-s3

workflows:
  version: 2
  test local venv:
    jobs:
      - test-local-venv
      - build-lambda-packages:
          requires:
            - test-local-venv
      - test-terraform-modules:
          requires:
            - build-lambda-packages
#      - push-lambda-packages-to-s3:
#          requires:
#            - build-lambda-packages
