
version: 2.1
executors:
  lambda-executor:
    docker:
      - image: circleci/python:3.7.2
    working_directory: /tmp

jobs:
  create-venv:
    executor: lambda-executor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: make create-all-venv

      - persist_to_workspace:
          root: /tmp

  test:
    executor: lambda-executor
    steps:
      - - attach_workspace:
            at: /tmp
            
      - run:
          name: run tests
          command: make test-all-venv
          environment:
            AWS_SECRET_ACCESS_KEY: "This_is_a_key"
            AWS_ACCESS_KEY_ID: "This_is_an_Id"
            BOTO_CONFIG: /dev/null

      - store_artifacts:
          path: pytest.report.html
          destination: pytest.report.html

workflows:
  version: 2
  build-test:
    jobs:
      - create-venv
      - test:
          requires:
            - create-venv
