
version: 2.1
jobs:
  create-venv:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: make create-all-venv

  test:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - run:
          name: run tests
          command: make test-all-venv
          environment:
            AWS_SECRET_ACCESS_KEY: "This_is_a_key"
            AWS_ACCESS_KEY_ID: "This_is_an_Id"
            BOTO_CONFIG: /dev/null

      - store_artifacts:
          path: pytest.report.html
          destination: pytest.report.html

workflows:
  version: 2
  build-test:
    jobs:
      - create-venv
      - test:
          requires:
            - create-venv
