version: 2.1
executors:
  lambda-executor:
    docker:
      - image: circleci/python:3.7.2
#    working_directory: /tmp

jobs:
  check-git-tag:
    executor: lambda-executor
    steps:
      - checkout
      - run:
          name: "Check git tag"
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then echo "No Build tag" && exit 0; fi
            export VERSION=$(grep version config.toml | cut -d'"' -f2)
            if [ ${CIRCLE_TAG} !=  ${VERSION} ]; then echo "Git tag ${CIRCLE_TAG} is different than the app version  ${VERSION}"; exit 1; fi


  test-python-lambdas:
    executor: lambda-executor
    steps:
      - checkout
      - run:
          name: "Pull git submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: run tests local venv
          command: |
            if [[ ! -z "${CIRCLE_TAG}" ]]; then export VERSION=${CIRCLE_TAG}; fi
            make python/lambda/test-all
          environment:
            AWS_SECRET_ACCESS_KEY: "This_is_a_key"
            AWS_ACCESS_KEY_ID: "This_is_an_Id"
            BOTO_CONFIG: /dev/null
      - store_test_results:
          path: ./results
      - store_artifacts:
          path: ./results
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-lambda-packages:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build lambda packages
          command: |
            if [[ ! -z "${CIRCLE_TAG}" ]]; then export VERSION=${CIRCLE_TAG}; fi
            make python/lambda/create-package
      - persist_to_workspace:
          root: .
          paths:
            - ./virtualenvs/*
            - ./packages/*
      - save_cache:
          key: package-shopper-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./packages/*

  test-terraform-modules:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test terraform modules
          command: |
            if [[ ! -z "${CIRCLE_TAG}" ]]; then export VERSION=${CIRCLE_TAG}; fi
            make terraform/test
      - store_test_results:
          path: ./results/terraform_test
      - store_artifacts:
          path: ./results/terraform_test
      - persist_to_workspace:
          root: .
          paths:
            - ./results/terraform_test/*

  copy-lambda-package-s3:
    executor: lambda-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - package-shopper-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Rename revision package to tagged build
          command: |
            cd packages
            rename .$(CIRCLE_SHA1} '' *.zip
            ls -ali
            cd -
      - run:
          name: copy package to S3
          command: |
            export VERSION=${CIRCLE_TAG}
            make aws/publish-lambda-packages-S3

workflows:
  version: 2
  Every build:
    jobs:
      - test-python-lambdas
      - build-lambda-packages:
          requires:
            - test-python-lambdas
      - test-terraform-modules:
          requires:
            - build-lambda-packages
  Tagged build:
    jobs:
      - check-git-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - copy-lambda-package-s3:
          requires:
            - check-git-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/