version: 2.1
executors:
  lambda-executor:
    docker:
      - image: circleci/python:3.7.2
#    working_directory: /tmp

jobs:
  test-local-venv:
    executor: lambda-executor
    #    docker:
    #      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: "Pull git submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: run tests local venv
          command: |
            make python/lambda/test-all
          environment:
            AWS_SECRET_ACCESS_KEY: "This_is_a_key"
            AWS_ACCESS_KEY_ID: "This_is_an_Id"
            BOTO_CONFIG: /dev/null
      - store_test_results:
          path: ./results
      - store_artifacts:
          path: ./results
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-lambda-packages:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build lambda packages
          command: |
            make python/lambda/package
      - persist_to_workspace:
          root: .
          paths:
            - ./terraform/shopper/packages/*
            - ./terraform/shopper/variable.version.tf

  test-terraform-modules:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: test terraform modules
          command: |
            make terraform/test
      - store_test_results:
          path: ./results/terraform_test
      - store_artifacts:
          path: ./results/terraform_test
      - persist_to_workspace:
          root: .
          paths:
            - ./results/terraform_test/*

  create-terraform-package:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: check folder content
          command: |
            ls -ali terraform/shopper/packages/
      - run:
          name: create terraform package
          command: |
            make create-terraform-package
      - persist_to_workspace:
          root: .
          paths:
            - ./terraform_module/*
      - store_artifacts:
          path: ./terraform_module

  push-terraform-module-to-s3:
    executor: lambda-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check package content
          command: |
            make --trace publish-packages-to-s3

workflows:
  version: 2
  test local venv:
    jobs:
      - test-local-venv
      - build-lambda-packages:
          requires:
            - test-local-venv
      - test-terraform-modules:
          requires:
            - build-lambda-packages
#      - test-terraform-modules:
#          requires:
#            - build-lambda-packages
#      - create-terraform-package:
#          requires:
#            - test-terraform-modules
#          filters:
#            branches:
#              only: master
#      - push-terraform-module-to-s3:
#          requires:
#            - create-terraform-package
#          filters:
#            branches:
#              only: master

#      - push-lambda-packages-to-s3:
#          requires:
#            - build-lambda-packages
