version: 1

update_configs:
  - package_manager: "python"
    directory: "/lambda/python/tiingo_fetcher"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/lambda/python/tiingo_scheduler"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/shared"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/tests"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/shopper/terraform"
    update_schedule: "daily"