version: 1

update_configs:
  - package_manager: "python"
    directory: "/lambda/python/market_data_resample"
    update_schedule: "weekly"

  - package_manager: "python"
    directory: "/lambda/python/tiingo_fetcher"
    update_schedule: "weekly"

  - package_manager: "python"
    directory: "/lambda/python/tiingo_scheduler"
    update_schedule: "weekly"

  - package_manager: "python"
    directory: "/shared"
    update_schedule: "weekly"

  - package_manager: "python"
    directory: "/tests"
    update_schedule: "weekly"

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "weekly"

  - package_manager: "terraform"
    directory: "/tests/shopper/terraform"
    update_schedule: "weekly"